### ISSUE TITLE
Use Helm Release Namespace

### ISSUE THREAD

**Issue by belfhi** [panosc-portal/panosc-portal-demo-deployment#2]
Hello,
I noticed that the namespace is done via `Values.panoscPortal.namespace` and not `.Release.Namespace`. Is there a reason why this is done?
Using the helm namespace would make deployment easier...
_edit:_ Is this because of the Helm3 requirement and helm3 not creating namespaces?

**Comment by MrWillTurner** [comment]
Hello, 
We are currently thinking about adding `.Release.Namespace`  since most of the other charts use it. However, we will still need to have a namespace in the values.yaml file to be able to create instances (via the cloudProviderKubernetes) in a separate namespace than the one where the portal is installed in.

**Comment by belfhi** [comment]
Is a second namespace even necessary?
Wouldn't it be more elegant to have all panosc portal resources in a namespace?
Just like jupyterhub user pods are created in the same namespace as the hub?
The official k8s documentation [1] also calls namespaces "virtual clusters"
Maybe that's only a personal preference though, it also makes DNS etc. easier 
when object share a namespace.

[1] https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/

**Comment by MrWillTurner** [comment]
The idea is to separate the application containers from the containers created for the remote desktop and jupyter notebook instances so that it is easier to manage both separately. 
Our architecture will also allow us to create other CloudProviders to create instances on other types of clusters (OpenStack, Slurm ..). It then makes sense that the Kubernetes cloud provider deploys the instances on another "virtual cluster".

**Comment by belfhi** [comment]
Seems like you've given it a lot of thought :) 
The argument with different cloud providers makes sense though!
Cheers

**Comment by MrWillTurner** [comment]
Well, thanks for the feedback.
I just implemented the `.Release.Namespace` into our new helm charts https://github.com/panosc-portal/helm-charts.

At the moment the new PaNOSC Portal Demo does not work but it should be in a couple of days.
